name: docs
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  docs:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v2

    # need python
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
        cache: 'pip'
    - run: pip install -r requirements.txt

    # fetch the Verilog from Wokwi API
    - name: fetch Verilog and build config
      run: ./configure.py --check-docs

